name: pyrefly-pydantic-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - typing-extensions=4.15.0
  - typing-inspection
  - annotated-types=0.7.0
  - pyrefly=0.33.0
